function config = x280XCPConfiguration
%X280XCPCONFIGURATION Return the fixed XCP-on-UDP wire configuration.

config = struct( ...
    'Transport', "UDP", ...
    'DefaultAddress', "192.168.0.106", ...
    'Port', 17725, ...
    'FrameHeaderBytes', 4, ...
    'MaxDTOBytes', 508, ...
    'MaxDatagramBytes', 512);
end
