function message = emptyFDMessage()
%EMPTYFDMESSAGE Vehicle Network Toolbox CAN_FD_MESSAGE_BUS layout.
%#codegen
message = struct('ProtocolMode', uint8(0), 'Extended', uint8(0), ...
    'Length', uint8(0), 'Remote', uint8(0), 'Error', uint8(0), ...
    'BRS', uint8(0), 'ESI', uint8(0), 'DLC', uint8(0), ...
    'ID', uint32(0), 'Reserved', uint32(0), 'Timestamp', 0.0, ...
    'Data', zeros(64, 1, 'uint8'));
end
