get_filename_component(_portable_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_portable_toolchain "${_portable_root}/toolchain")
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER "${_portable_toolchain}/bin/linux-gcc.exe")
set(CMAKE_CXX_COMPILER "${_portable_toolchain}/bin/linux-g++.exe")
set(CMAKE_AR "${_portable_toolchain}/bin/linux-ar.exe")
set(CMAKE_RANLIB "${_portable_toolchain}/bin/linux-ranlib.exe")
set(CMAKE_STRIP "${_portable_toolchain}/bin/linux-strip.exe")
set(CMAKE_SYSROOT "${_portable_toolchain}/x86_64-linux")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
# Compiler helpers are native Windows programs. No MSYS shell is needed.
set(ENV{PATH} "${_portable_toolchain}/bin;${_portable_root}/host-bin;$ENV{PATH}")
foreach(_variable GCC_EXEC_PREFIX COMPILER_PATH LIBRARY_PATH CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH OBJC_INCLUDE_PATH)
    unset(ENV{${_variable}})
endforeach()
