function onHardwareSelect(hCS)
%ONHARDWARESELECT Make selecting the board enable the complete local build.
set_param(hCS, 'GenCodeOnly', 'off', 'EnableMultiTasking', 'off', ...
    'ConcurrentTasks', 'off', 'TargetLang', 'C', 'ExtMode', 'on', ...
    'GenerateASAP2', 'off', 'DefaultParameterBehavior', 'Tunable');
model = getModel(hCS);
if ~isempty(model) && model ~= 0
    coder.coverage.BuildHook.addHook(model, ...
        'codertarget.x280linuxssh.internal.LocalBuildHook', ...
        'IncludeReferencedModels', 'off');
end
end
